spring:

  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  #    password:

  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username:
    # 配置密码，邮箱申请到的授权码
    password:
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

mybatis-plus:
  global-config:
    db-config:
      table-prefix: pzhu_
      # 逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration-properties:
    prefix: pzhu_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置mapper xml文件的路径
  mapper-locations: classpath:com/pzhu/substitute/mapper/xml/*.xml
  # 枚举转换的包
  type-enums-package: com.pzhu.substitute.common.status

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: DrivingConsumerGroup

aliyun:
  oss:
    file:
      endpoint: oss-cn-qingdao.aliyuncs.com
      keyid:
      keysecret:
      bucketname: pzhu-substitute-driving
      filehost:


